name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Setting up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Installing pm2
        run: npm install pm2@latest -g

      - name: executing ssh commands remotely
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh    
            sh /home/ubuntu/server/deploy.sh
