name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: executing ssh commands remotely
        uses: appleboy/ssh-action@master
        run: npm install pm2 -g
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: sh /home/ubuntu/server/deploy.sh
